[project]
name = "new-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "deepagents>=0.2.8",
    "dotenv>=0.9.9",
    "langchain>=1.0.8",
    "langchain-anthropic>=1.2.0",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=3.1.0",
    "langchain-tavily>=0.2.13",
    "langgraph>=1.0.3",
    "langgraph-checkpoint-postgres>=3.0.1",
    "langgraph-cli>=0.4.7",
    "langgraph-sdk>=0.2.9",
    "psycopg[binary,pool]>=3.2.13",
    "tavily>=1.1.0",
]

[dependency-groups]
dev = [
    "langgraph-cli[inmem]>=0.4.7",
]
