[project]
name = "new-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.0.8",
    "langchain-google-genai>=3.1.0",
    "langgraph>=1.0.3",
    "langgraph-sdk>=0.2.9",
]

[dependency-groups]
dev = [
    "langgraph-cli[inmem]>=0.4.7",
]
